---
- name: Install Python libraries for Docker
  # WORKAROUND https://gitlab.inria.fr/discovery/enoslib/-/issues/202
  pip:
    name:
      - "docker<7.1.0"
      - "requests<2.32"
    state: present
    extra_args: "--ignore-installed"

- name: Grant read/write access to Docker socket for monitoring agents
  file:
    path: /var/run/docker.sock
    mode: '0666'
  ignore_errors: yes

- name: Installing Telegraf
  docker_container:
    name: telegraf
    image: "{{ agent_image }}"
    detach: yes
    state: started
    recreate: yes
    network_mode: host
    device_requests: "{{ c_device_request }}"
    volumes:
      - "{{ remote_working_dir }}/telegraf.conf:/etc/telegraf/telegraf.conf"
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env: "{{ c_env }}"
