---
galaxy_info:
  author: Sylvain Baubeau
  description: Skydive Commons
  company: Red Hat
  license: Apache License, Version 2.0
  min_ansible_version: 2.3
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
