- name: Create docker config directory
  file:
    path: /etc/docker/
    state: directory

- name: Allow Docker to use an insecure registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: Restart docker daemon
