---
- name: "Installing the rpmfusion repo packages"
  dnf: name=['http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm']
       state=present

- name: "Install copr dnf plugin"
  package:
    name: dnf-plugins-core
    state: present
