---
- selinux:
    policy: targeted
    state: permissive

- shell: yum -y copr enable ganto/lxc3

- package:
    name: lxc
    state: present

- package:
    name: lxd
    state: present

- lineinfile:
    path: /etc/subuid
    line: 'root:1000000:65536'

- lineinfile:
    path: /etc/subgid
    line: 'root:1000000:65536'

- shell: |
    grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
    grubby --args="namespace.unpriv_enable=1" --update-kernel="$(grubby --default-kernel)"
  when: ansible_distribution == "CentOS"

- copy:
    content: user.max_user_namespaces=3883
    dest: /etc/sysctl.d/99-userns.conf
    mode: 0644
  when: ansible_distribution == "CentOS"

- service:
    name: lxd
    state: started
    enabled: yes

- file:
    src: /var/run/lxd.socket
    dest: /var/lib/lxd/unix.socket
    state: link

- shell: "systemctl enable lxd"

- shell: "lxd init --auto"
