---
- package:
    name: "{{ item }}"
    state: present
  with_items:
     - glibc-static
     - xz-static
     - zlib-static
     - flex
     - bison
     - byacc
     - libxml2-static
- shell: |
    cd /tmp
    rm -rf libpcap
    git clone https://github.com/the-tcpdump-group/libpcap.git
    cd libpcap
    git checkout libpcap-1.5.3
    curl http://'git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -o config.guess
    curl http://'git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -o config.sub
    ./configure --prefix=/usr/local --disable-shared --disable-dbus --disable-bluetooth --disable-canusb
    make
    sudo make install
