# -*- coding: utf-8 -*-

JOB_TYPE_DEPLOY = "deploy"
DEFAULT_ENV_NAME = "debian9-x64-nfs"
DEFAULT_JOB_NAME = "EnOSlib"
DEFAULT_JOB_TYPE = JOB_TYPE_DEPLOY
DEFAULT_QUEUE = "default"
DEFAULT_WALLTIME = "02:00:00"
DEFAULT_NUMBER = 1

NAMESERVER = "dns.grid5000.fr"
