---
- name: Deploy Skydive development machine
  hosts: dev
  become: yes
  pre_tasks:
  - selinux: state=disabled
  - shell: setenforce 0
  roles:
  - role: elasticsearch
  - role: orientdb
  - role: skydive_dev
