---
- name: Iptables allow embedded etcd server port
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    source: "{{ item | regex_replace('([^:]*).+', '\\1') }}"
    destination_port: "{{ skydive_etcd_port | string }}"
    jump: ACCEPT
    comment: "Skydive: embedded etcd port"
    action: insert
  when: (skydive_etcd_embedded | bool)
  with_items: "{{ analyzers.split(',') | list }}"

- name: Iptables allow embedded etcd client port
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    source: "{{ item | regex_replace('([^:]*).+', '\\1') }}"
    destination_port: "{{ (skydive_etcd_port + 1) | string }}"
    jump: ACCEPT
    action: insert
    comment: "Skydive: embedded etcd port"
  when: (skydive_etcd_embedded | bool)
  with_items: "{{ analyzers.split(',') | list }}"

- name: Iptables allow API port
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: "{{ skydive_analyzer_port }}"
    jump: ACCEPT
    action: insert
    comment: "Skydive: API port"

- name: Iptables get generated rules
  shell: "iptables-save | grep Skydive:"
  register: iptables_rules

- name: Iptables generated new rules file Red Hat
  copy:
    content: |
      # Generated by skydive-ansible
      *filter
      :INPUT ACCEPT [0:0]
      :FORWARD ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      COMMIT
    dest: /etc/sysconfig/iptables
    force: no
    group: root
    owner: root
    mode: 0600
  when: (ansible_os_family == 'RedHat') or (ansible_distribution == 'Fedora')

- name: Iptables remove previous persistent rules Red Hat
  lineinfile:
    path: /etc/sysconfig/iptables
    regexp: "Skydive: "
    state: absent
  when: (ansible_os_family == 'RedHat') or (ansible_distribution == 'Fedora')

- name: Iptables make rules persistent Red Hat
  lineinfile:
    path: /etc/sysconfig/iptables
    line: "{{ item }}"
    insertbefore: "^COMMIT$"
  with_items: "{{ iptables_rules.stdout_lines }}"
  when: (ansible_os_family == 'RedHat') or (ansible_distribution == 'Fedora')

- name: Iptables generated new rules file Debian/Ubuntu
  copy:
    content: |
      # Generated by skydive-ansible
      *filter
      :INPUT ACCEPT [0:0]
      :FORWARD ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      COMMIT
    dest: /etc/iptables/rules.v4
    force: no
    group: root
    owner: root
    mode: 0600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Iptables remove previous persistent rules Debian/Ubuntu
  lineinfile:
    path: /etc/iptables/rules.v4
    regexp: "Skydive: "
    state: absent
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Iptables make rules persistent Debian/Ubuntu
  lineinfile:
    path: /etc/iptables/rules.v4
    line: "{{ item }}"
    insertbefore: "^COMMIT$"
  with_items: "{{ iptables_rules.stdout_lines }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'