---
- name: Gather facts
  hosts: all
  tasks:
  - name: Gather facts on all hosts
    setup: {}

- name: Monitoring - Telegraf agents
  hosts: telegraf
  roles:
  - telegraf

- name: Monitoring - InfluxDB collector
  hosts: influxdb
  roles:
  - influxdb

- name: Monitoring - Prometheus collector
  hosts: prometheus
  roles:
  - prometheus

- name: Monitoring - Grafana UI
  hosts: grafana
  roles:
  - grafana
